### PR TITLE
870 when inviting an extern error message is in english

### LINKED ISSUE #870: when inviting an extern, error message is in english
steps to reproduce:
- create a private room without extern
- invite an extern by email :  

I would prefer to understand why I can't invite this person. The system should point out that the room is not admitting external people

same issue in web : https://github.com/tchapgouv/tchap-web-v4/issues/253

IMG_F04A452F7D48-1

### PR DESCRIPTION
**Pull request by NicolasBuquet**
Fix #870 

Simulator Screenshot - iPhone 14 - 2023-10-23 at 17 46 05

### CODE REVIEW

File: Riot/Modules/Room/ParticipantsInviteModal/ContactsPicker/ContactsPickerViewModel.swift [hunk 1]
```diff
@@ -128,7 +128,9 @@ class ContactsPickerViewModel: NSObject, ContactsPickerViewModelProtocol {
         contactsViewController.showSearch(true)
         // Tchap: Replace string by removing user ID
         contactsViewController.searchBar.placeholder = VectorL10n.roomParticipantsInviteAnotherUserWithoutId
-        contactsViewController.searchBar.resignFirstResponder()
+        // Tchap: don't make searchbar rersign as first responder.
```
Comment (yostyle) [inline Riot/Modules/Room/ParticipantsInviteModal/ContactsPicker/ContactsPickerViewModel.swift:131]: rersign <= typo ?

**Review by yostyle — CHANGES_REQUESTED** [review]

File: Riot/Modules/Room/ParticipantsInviteModal/ContactsPicker/ContactsPickerViewModel.swift (hunk 1 above)
Comment (NicolasBuquet) [reply Riot/Modules/Room/ParticipantsInviteModal/ContactsPicker/ContactsPickerViewModel.swift:131]: Yes. -> resign

**Review by yostyle — APPROVED** [review]
